# Generated by Django 5.1.4 on 2025-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originText', models.TextField()),
                ('inferenceText', models.TextField()),
                ('task_type', models.CharField(max_length=100)),
            ],
        ),
    ]
