# Generated by Django 5.1.4 on 2025-01-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinference',
            name='inferenceText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='textinference',
            name='originText',
            field=models.TextField(),
        ),
    ]
