# Generated by Django 5.1.4 on 2025-01-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0002_alter_textinference_inferencetext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinference',
            name='user_ip',
            field=models.CharField(default='-1.-1.-1.-1', max_length=100),
        ),
    ]
