# Generated by Django 5.1.4 on 2025-01-16 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_textinference_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinference',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 5, 29, 21, 25947)),
        ),
    ]
