# Generated by Django 5.1.4 on 2025-02-03 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_textinference_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinference',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 2, 53, 15, 515818, tzinfo=datetime.timezone.utc)),
        ),
    ]
